src/SafetyStore.Web/Models/ErrorViewModel.cs
namespace SafetyStore.Web.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

src/SafetyStore.Web/Controllers/AuthController.cs
using Microsoft.AspNetCore.Mvc;
using SafetyStore.Application.DTO;

namespace SafetyStore.Web.Controllers
{
    [Route("api/[controller]")]
    [ApiController]
    public class AuthController : ControllerBase
    {
        [HttpPost("login")]
        public IActionResult Login([FromBody] UserLoginRequest request)
        {
            return Ok();
        }

        [HttpPost("register")]
        public IActionResult Register([FromBody] UserRegisterRequest request)
        {
            return Ok();
        }
    }
}

src/SafetyStore.Web/Controllers/DetailsController.cs
using Microsoft.AspNetCore.Mvc;

namespace SafetyStore.Web.Controllers
{
    public class DetailsController : Controller
    {
        public IActionResult Team()
        {
            return View();
        }

        public IActionResult License()
        {
            return View();
        }

        public IActionResult Contact()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }
    }
}

src/SafetyStore.Web/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using SafetyStore.Web.Models;
using System.Diagnostics;

namespace SafetyStore.Web.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Features()
        {
            return View();
        }

        public IActionResult About()
        {
            return View();
        }


        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

src/SafetyStore.Web/Views/Details/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}

<h1>Contact</h1>

src/SafetyStore.Web/Views/Details/License.cshtml
@{
    ViewData["Title"] = "License";
}

<h1>License</h1>

src/SafetyStore.Web/Views/Details/Team.cshtml
@{
    ViewData["Title"] = "Team";
}

<h1>Team</h1>

src/SafetyStore.Web/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About Service";
}

<h1>About Service</h1>

src/SafetyStore.Web/Views/Home/Features.cshtml
@{
    ViewData["Title"] = "Features";
}

<h1>Features</h1>

src/SafetyStore.Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

@section Scripts {
    <script type="module" src="~/js/index.js" ></script>
}

@section Styles {
    <link rel="stylesheet" href="~/css/index.css"/>
}

<div id="turtle-container">
    
</div>

src/SafetyStore.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SafetyStore</title>

    <link rel="stylesheet" href="~/css/main.css"/>
    @await RenderSectionAsync("Styles", required: false)
</head>
<body>
    <header class="bg-white">
        <nav aria-label="Global" class="mx-auto flex max-w-7xl items-center justify-between p-6 lg:px-8">
            <div class="flex lg:flex-1">
                <a asp-controller="Home" asp-action="Index" class="-m-1.5 p-1.5">
                    <span class="sr-only">Safety Store</span>
                    <img src="https://tailwindcss.com/plus-assets/img/logos/mark.svg?color=indigo&shade=600" alt="" class="h-8 w-auto" />
                </a>
            </div>
            <div class="flex lg:hidden">
                <button type="button" command="show-modal" commandfor="mobile-menu" class="-m-2.5 inline-flex items-center justify-center rounded-md p-2.5 text-gray-700">
                    <span class="sr-only">Open main menu</span>
                    <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" data-slot="icon" aria-hidden="true" class="size-6">
                        <path d="M3.75 6.75h16.5M3.75 12h16.5m-16.5 5.25h16.5" stroke-linecap="round" stroke-linejoin="round" />
                    </svg>
                </button>
            </div>
            <el-popover-group class="hidden lg:flex lg:gap-x-12">
                <a asp-controller="Home" asp-action="Index" class="text-sm/6 font-semibold text-gray-900">Home</a>
                <a asp-controller="Home" asp-action="Features" class="text-sm/6 font-semibold text-gray-900">Features</a>
                <a asp-controller="Home" asp-action="About" class="text-sm/6 font-semibold text-gray-900">About</a>
            </el-popover-group>
            <div class="hidden lg:flex lg:flex-1 lg:justify-end">
                <a href="#" class="text-sm/6 font-semibold text-gray-900">Log in <span aria-hidden="true">&rarr;</span></a>
            </div>
        </nav>
        <el-dialog>
            <dialog id="mobile-menu" class="backdrop:bg-transparent lg:hidden">
                <div tabindex="0" class="fixed inset-0 focus:outline-none">
                    <el-dialog-panel class="fixed inset-y-0 right-0 z-50 w-full overflow-y-auto bg-white p-6 sm:max-w-sm sm:ring-1 sm:ring-gray-900/10">
                        <div class="flex items-center justify-between">
                            <a href="#" class="-m-1.5 p-1.5">
                                <span class="sr-only">Safety Store</span>
                                <img src="https://tailwindcss.com/plus-assets/img/logos/mark.svg?color=indigo&shade=600" alt="" class="h-8 w-auto" />
                            </a>
                            <button type="button" command="close" commandfor="mobile-menu" class="-m-2.5 rounded-md p-2.5 text-gray-700">
                                <span class="sr-only">Close menu</span>
                                <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" data-slot="icon" aria-hidden="true" class="size-6">
                                    <path d="M6 18 18 6M6 6l12 12" stroke-linecap="round" stroke-linejoin="round" />
                                </svg>
                            </button>
                        </div>
                        <div class="mt-6 flow-root">
                            <div class="-my-6 divide-y divide-gray-500/10">
                                <div class="space-y-2 py-6">
                                    <a asp-controller="Home" asp-action="Index" class="-mx-3 block rounded-lg px-3 py-2 text-base/7 font-semibold text-gray-900 hover:bg-gray-50">Home</a>
                                    <a asp-controller="Home" asp-action="Features" class="-mx-3 block rounded-lg px-3 py-2 text-base/7 font-semibold text-gray-900 hover:bg-gray-50">Features</a>
                                    <a asp-controller="Home" asp-action="About" class="-mx-3 block rounded-lg px-3 py-2 text-base/7 font-semibold text-gray-900 hover:bg-gray-50">About</a>
                                </div>
                                <div class="py-6">
                                    <a href="#" class="-mx-3 block rounded-lg px-3 py-2.5 text-base/7 font-semibold text-gray-900 hover:bg-gray-50">Log in</a>
                                </div>
                            </div>
                        </div>
                    </el-dialog-panel>
                </div>
            </dialog>
        </el-dialog>
    </header>

    <main role="main" class="app">
        @RenderBody()
    </main>

    <footer class="bg-white rounded-lg shadow-sm m-4">
        <div class="w-full mx-auto max-w-screen-xl p-4 md:flex md:items-center md:justify-between">
            <span class="text-sm text-gray-500 sm:text-center text-gray-400">
                &copy; 2025 All Rights Reserved.
            </span>
            <ul class="flex flex-wrap items-center mt-3 text-sm font-medium text-gray-500 text-gray-400 sm:mt-0">
                <li>
                    <a asp-controller="Home" asp-action="About" class="hover:underline me-4 md:me-6">About</a>
                </li>
                <li>
                    <a asp-controller="Details" asp-action="Privacy" class="hover:underline me-4 md:me-6">Privacy Policy</a>
                </li>
                <li>
                    <a asp-controller="Details" asp-action="License" class="hover:underline me-4 md:me-6">Licensing</a>
                </li>
                <li>
                    <a asp-controller="Details" asp-action="Contact" class="hover:underline">Contact</a>
                </li>
            </ul>
        </div>
    </footer>

    <script src="~/js/theme.js" asp-append-version="true"></script>
    <script src="~/js/app.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>